# Generated by Django 6.1.1 on 2026-09-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pun_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qestion_text',
            new_name='question_text',
        ),
    ]
